package com.cts.training.day5;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("productName")
	private java.lang.String productName;
	@org.kie.api.definition.type.Label("productPrice")
	private double productPrice;
	@org.kie.api.definition.type.Label("discount")
	private double discount;

	private java.lang.String type;

	public Product() {
	}

	public java.lang.String getProductName() {
		return this.productName;
	}

	public void setProductName(java.lang.String productName) {
		this.productName = productName;
	}

	public double getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(double productPrice) {
		this.productPrice = productPrice;
	}

	public double getDiscount() {
		return this.discount;
	}

	public void setDiscount(double discount) {
		this.discount = discount;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public Product(java.lang.String productName, double productPrice,
			double discount, java.lang.String type) {
		this.productName = productName;
		this.productPrice = productPrice;
		this.discount = discount;
		this.type = type;
	}

}